version: '2.1'
services:
  zookeeper:
    image: confluent/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    build: docker/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_LOG_RETENTION_HOURS=1
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_CREATE_TOPICS=AccountTopic:5:1
      - KAFKA_NUM_PARTITIONS=5
      - KAFKA_DELETE_RETENTION_MS=1000
      - KAFKA_JMX_PORT=3099
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=3099
